#pragma once

#include "NativeGameplayTags.h"

namespace CommonTrainTags
{
	COMMONTRAIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Forward)
	COMMONTRAIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stopping)
	COMMONTRAIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StopIntro)
	COMMONTRAIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StopOutro)
	COMMONTRAIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Backward)
}
